version: '3.7'

services:
  service-discovery:
    image: golang:1.15.6-alpine
    build: ./
    command: ./bin/service-discovery
    restart: always
    container_name: service-discovery
    environment:
      ETCD_ADDR: 192.168.0.33:2379,192.168.0.24:2379,192.168.0.50:2379
      SERVICE_DISCOVERY_INSTANCE: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - etcd-network
      - core-network

networks:
  etcd-network:
    external: true
  core-network:
    external: true